# Generated by Django 5.2.1 on 2025-12-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_tag_snippet_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="extension",
            field=models.CharField(
                default="txt", max_length=10, verbose_name="Extension"
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(fields=["user"], name="snippets_sn_user_id_ae9a03_idx"),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["is_public"], name="snippets_sn_is_publ_c3385b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["created_at"], name="snippets_sn_created_b92b4c_idx"
            ),
        ),
    ]
