FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    UV_SYSTEM_PYTHON=1 \
    UV_PYTHON=/usr/local/bin/python3.13 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.14 /uv /uvx /bin/

# Put venv binaries first
ENV PATH="/app/.venv/bin:$PATH"

# Install dependencies (WITHOUT installing Python)
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

ENV PYTHONPATH=/app

# Copy full pyproject + lockfile
COPY pyproject.toml uv.lock* ./

# Install project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

# Copy application
COPY . .

EXPOSE 8000

CMD ["uv", "run", "gunicorn", "--bind", "0.0.0.0:8000", "--worker-class", "uvicorn.workers.UvicornWorker", "core.asgi:application"]
